# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-06 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=512)),
                ('achternaam', models.CharField(max_length=512)),
            ],
        ),
    ]
