# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-06 00:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_auto_20191206_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=512)),
                ('achternaam', models.CharField(max_length=512)),
            ],
        ),
        migrations.AddField(
            model_name='likes',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pizza.UserProfile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pizzeria',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pizza.UserProfile'),
            preserve_default=False,
        ),
    ]
